#%RAML 1.0 Library
types:
  carExample: !include example/carExample.json
  customerExample: !include example/customerExample.json
  rentalExample: !include example/rentalExample.json
  carDataType: !include dataType/carDataType.raml
  customerDataType: !include dataType/customerDataType.raml
  rentalDataType: !include dataType/rentalDataType.raml
  
  # carResourceType: !include resourceType/carResourceType.raml
  # customerResource: !include resourceType/customerResourceType.raml
  # rentalResource: !include resourceType/rentalResourceType.raml
