#%RAML 1.0 ResourceType
get:
    description: get list of customers
    responses:
       200: 
         description: successful.
         body:
          application/json:
            type: !include ../datatype/dataType.raml
            example: !include ../example/example.json
post:
  description: Storing customer data.
  body:
    application/json:
      type: !include ../datatype/dataType.raml
      example: !include ../example/example.json
  responses:
    201:
      description: successful.
      body:
        application/json:
          type: string
          example: "successful"
put:
  description: updating customer data.
  body:
    application/json:
      type: object
      properties:
        customerID:
          type: integer
          description: customer identification number.
          required: true
        customerName:
          type: string
          description: name of the customer.
          required: true
        channel:
          type: string
          description: how is the customer reaching out.
          required: true
        message:
          type: string
          description: customer feedback
          required: true
        rating:
          type: integer
          description: customer score about the service.
          required: true
      example:
        customerID: 675
        customerName: "micheal"
        channel: "email"
        message: "the service was good"
        rating: 4
   responses:
    200:
      body:
        application/json:
          type: string
          example: "updated successfuly"
  delete:
     description: deleting customer data.
     responses:
       204:
         body:
           application/json:
             type: string
             example: "deleted"