#%RAML 1.0 ResourceType
uses:
  mylib: /exchange_modules/1198ba5d-0d49-4948-8298-87857ff806a5/walmart-library/1.0.1/walmart-library.raml  
get:
    description: Provide stock status of grocery items from internal database.
    queryParameters:
      itemId:
        type: integer
        example: 5341239784
      stock:
        type: boolean
        example: true
      lastUpdated:
        type: datetime
        example: "2025-06-19T16:17:37Z"                  
    responses:
      200:
        description: Successful
        body:
          application/json:
            type: mylib.inventory
            example: !include ../example/inventoryExample.json
